In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\gaayushi\OneDrive - VMware, Inc\VMwareCorp\Desktop\FoodBalanceSheets_E_Africa_NOFLAG.csv", encoding = "latin-1")

In [3]:
df.head()

Area Code     Area  Item Code         Item  Element Code  \
0          4  Algeria       2501   Population           511   
1          4  Algeria       2501   Population          5301   
2          4  Algeria       2901  Grand Total           664   
3          4  Algeria       2901  Grand Total           674   
4          4  Algeria       2901  Grand Total           684   

                                  Element             Unit     Y2014  \
0           Total Population - Both sexes     1000 persons  38924.00   
1                Domestic supply quantity      1000 tonnes      0.00   
2           Food supply (kcal/capita/day)  kcal/capita/day   3377.00   
3  Protein supply quantity (g/capita/day)     g/capita/day     94.90   
4      Fat supply quantity (g/capita/day)     g/capita/day     80.06   

      Y2015     Y2016     Y2017     Y2018  
0  39728.00  40551.00  41389.00  42228.00  
1      0.00      0.00      0.00      0.00  
2   3379.00   3372.00   3341.00   3322.00  
3     94.35     94.72     92.82     91.83  
4     79.36     77.40     80.19     77.28

In [4]:
df.isnull().sum()

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

In [5]:
missing_percentage = ((df.isnull().sum() / len(df)) * 100).round(3)
missing_percentage

Area Code       0.000
Area            0.000
Item Code       0.000
Item            0.000
Element Code    0.000
Element         0.000
Unit            0.000
Y2014           2.607
Y2015           2.540
Y2016           2.519
Y2017           2.471
Y2018           2.356
dtype: float64

In [6]:
stock_df = df[df['Element'] == 'Stock Variation']

# Group by 'Element' and find the sum of stock variation for each year
grouped = stock_df.groupby('Element').sum()

# Find the year with the highest sum of stock variation
grouped

Area Code                                               Area  \
Element                                                                         
Stock Variation     571566  AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...   

                 Item Code                                               Item  \
Element                                                                         
Stock Variation   11329527  Cereals - Excluding BeerWheat and productsRice...   

                 Element Code  \
Element                         
Stock Variation      21464704   

                                                              Unit     Y2014  \
Element                                                                        
Stock Variation  1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...  58749.83   

                    Y2015     Y2016     Y2017     Y2018  
Element                                                  
Stock Variation  34910.99  33140.12  54316.91  20577.91

In [7]:
arr = np.array([[94, 89, 63],

             [93, 92, 48],

             [92, 94, 56]])

In [8]:
arr[:2,1:]

array([[89, 63],
       [92, 48]])

In [9]:
arr[:2,0:]

array([[94, 89, 63],
       [93, 92, 48]])

In [10]:
arr[:1,1:]

array([[89, 63]])

In [11]:
arr[1:,:]

array([[93, 92, 48],
       [92, 94, 56]])

In [12]:
num_df = df.select_dtypes(include=['number'])
correlations = num_df.corr()['Element Code']
correlations

Area Code      -0.000209
Item Code      -0.024683
Element Code    1.000000
Y2014           0.024457
Y2015           0.023889
Y2016           0.023444
Y2017           0.024254
Y2018           0.024279
Name: Element Code, dtype: float64

In [13]:
my_tuppy = (1,2,5,8)

my_tuppy[2] = 6

TypeError: 'tuple' object does not support item assignment

In [14]:
sum_df = df[df['Element'] == 'Processing']
# Group by 'Element' and find the sum of stock variation for each year

total_processing_2017 = sum_df['Y2017'].sum()
total_processing_2017

292836.0

In [15]:
len(df['Area'].unique())

49

In [16]:
S = [['him', 'sell'], [90, 28, 43]]

S[0][1][1]

'e'

In [17]:
# Step 1: Select columns 'Y2017' and 'Area'
selected_columns = df[['Y2017', 'Area']]

# Step 2: Perform groupby operation and sum
grouped = selected_columns.groupby('Area').sum()

# Step 3: Sort the DataFrame in ascending order based on the sum of 'Y2017'
sorted_grouped = grouped.sort_values(by='Y2017')

# Step 4: Retrieve the Area with the 7th lowest sum
seventh_lowest_area = sorted_grouped.index[6]  # Indexing starts from 0

print("Area with the 7th lowest sum in 2017:", seventh_lowest_area)

Area with the 7th lowest sum in 2017: Guinea-Bissau


In [18]:
mean_2017 = df['Y2017'].mean()
std_dev_2017 = df['Y2017'].std()

# Round mean and standard deviation to 2 decimal places
mean_2017_rounded = round(mean_2017, 2)
std_dev_2017_rounded = round(std_dev_2017, 2)

print(mean_2017_rounded)
print(std_dev_2017_rounded)

140.92
1671.86


In [19]:
# Given list
lst = [[35, 'Portugal', 94], [33, 'Argentina', 93], [30 , 'Brazil', 92]]
col = ['Age', 'Nationality', 'Overall']

# Create DataFrame
df1 = pd.DataFrame(lst, columns=col, index = [1,2,3])

# Display DataFrame
print(df1)

   Age Nationality  Overall
1   35    Portugal       94
2   33   Argentina       93
3   30      Brazil       92


In [20]:
madagascar_protein_2015 = df[(df['Area'] == 'Madagascar') & (df['Element'] == 'Protein supply quantity (g/capita/day)')]

# Calculate the total Protein supply quantity in Madagascar in 2015
total_protein_supply_2015 = madagascar_protein_2015['Y2015'].sum()
total_protein_supply_2015

173.04999999999998

In [21]:
grouped = df.groupby('Area')['Y2017'].sum()

# Find the area with the highest sum in 2017
area_highest_sum_2017 = grouped.idxmax()

print("Area with the highest sum in 2017:", area_highest_sum_2017)

Area with the highest sum in 2017: Nigeria


In [23]:
# Filter the DataFrame to include only rows where the 'Item' is 'Wine'
wine_df = df[df['Item'] == 'Wine']

# Perform groupby sum aggregation on 'Item' for 2015
wine_2015_sum = wine_df['Y2015'].sum()

# Perform groupby sum aggregation on 'Item' for 2018
wine_2018_sum = wine_df['Y2018'].sum()

print(wine_2015_sum)
print(wine_2018_sum)

4251.8099999999995
4039.3199999999997
